{"name":"Mathlib.Lean.Exception","instances":[],"imports":["Init","Lean"],"declarations":[{"sourceLink":"https://github.com/leanprover-community/mathlib4/blob/44c828ca5b12983ef1d4eea5c54f95c2ef52cb36/Mathlib/Lean/Exception.lean#L27-L28","name":"Lean.Exception.isFailedToSynthesize","kind":"def","docLink":"./Mathlib/Lean/Exception.html#Lean.Exception.isFailedToSynthesize","doc":"Check if an exception is a \"failed to synthesize\" exception.\n\nThese exceptions are raised in several different places,\nand the only commonality is the prefix of the string, so that's what we look for.\n"},{"sourceLink":"https://github.com/leanprover-community/mathlib4/blob/44c828ca5b12983ef1d4eea5c54f95c2ef52cb36/Mathlib/Lean/Exception.lean#L12-L15","name":"successIfFail","kind":"def","docLink":"./Mathlib/Lean/Exception.html#successIfFail","doc":"A generalisation of `fail_if_success` to an arbitrary `MonadError`.\n"}]}